#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Feb 10 21:04:24 2022

@author: fanchao
"""

from yellowbrick.cluster import KElbowVisualizer
from sklearn.cluster import KMeans
import numpy as np

def elbow(tfidf_matrix):
    model = KMeans()
    # k is range of number of clusters.
    K = []
    for i in range(10):
        visualizer = KElbowVisualizer(model, k=(2,30), timings= False)
        visualizer.fit(tfidf_matrix)        # Fit data to visualizer   
        #visualizer.show()                                # Finalize and render figure
        k = visualizer.elbow_value_
        K.append(k)
    
    return np.mean(K),np.std(K)

